name: calwin
description: A smart Calender application.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.0
  provider: ^5.0.0
  rive: ^0.7.3
  font_awesome_flutter: ^9.0.0
  table_calendar: ^2.3.3
  loading: ^1.0.2
  shared_preferences: ^2.0.5
  animated_text_kit: ^4.0.0
  http: ^0.13.1
  google_fonts:
  intl: ^0.17.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.3
  flutter_form_builder:
  flutter_riverpod:
  datetime_picker_formfield: ^2.0.0
  flutter_datetime_picker: ^1.5.0
  flutter_cupertino_date_picker: ^1.0.26+2
  firebase_helpers: ^0.3.1
  uuid: 3.0.3
  page_transition: "^1.1.7+6"
  tuple: ^2.0.0
  slide_drawer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/google_logo.png
     - assets/bgtop.jpeg
     - assets/marty_v6.riv
     - assets/buggy.riv
     - assets/turtle.riv
     - assets/default_profile.png
     - assets/view_event_img.png

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
